/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutMotorRouteImport } from './routes/_layout/motor'
import { Route as LayoutFlashRouteImport } from './routes/_layout/flash'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMotorRoute = LayoutMotorRouteImport.update({
  id: '/motor',
  path: '/motor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFlashRoute = LayoutFlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/flash': typeof LayoutFlashRoute
  '/motor': typeof LayoutMotorRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/flash': typeof LayoutFlashRoute
  '/motor': typeof LayoutMotorRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/flash': typeof LayoutFlashRoute
  '/_layout/motor': typeof LayoutMotorRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/flash' | '/motor' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/flash' | '/motor' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/flash'
    | '/_layout/motor'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/motor': {
      id: '/_layout/motor'
      path: '/motor'
      fullPath: '/motor'
      preLoaderRoute: typeof LayoutMotorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/flash': {
      id: '/_layout/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof LayoutFlashRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutFlashRoute: typeof LayoutFlashRoute
  LayoutMotorRoute: typeof LayoutMotorRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFlashRoute: LayoutFlashRoute,
  LayoutMotorRoute: LayoutMotorRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
